### ISSUE TITLE
Reaper not clearing snapshots for failed segments

### ISSUE THREAD

**Issue by sandeepmallik** [thelastpickle/cassandra-reaper#666] opened 2019-05-16 10:16 UTC
Snapshots created from repair for failed segments are not getting cleared by reaper tool. Snapshots are accumulating and we have to clear them manually for now. Is there a way around to fix this?

Reaper Version - 1.4.2
Cassandra Version - 3.0.18

ERROR [RMI TCP Connection(36079)-127.0.0.1] 2019-05-08 13:33:06,811 RepairRunnable.java:272 - **Repair session d026f2b0-7195-11e9-98e2-b99243193fa5** for range [(4227378850225105567,4611686018427387892]] failed with error Terminate session is called
java.io.IOException: Terminate session is called
        at org.apache.cassandra.service.ActiveRepairService.terminateSessions(ActiveRepairService.java:190) ~[apache-cassandra-3.0.18.jar:3.0.18]
        at org.apache.cassandra.service.StorageService.forceTerminateAllRepairSessions(StorageService.java:3348) [apache-cassandra-3.0.18.jar:3.0.18]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
...

![snapshots](https://user-images.githubusercontent.com/12246569/57845462-b3dcec80-77ef-11e9-87e8-660795a2e73b.png)

**Comment by eriksw** [comment] 2019-05-21 23:04
Duplicate of #115 

(I'm also affected—This needs a fix in Reaper.)

**Comment by adejanovski** [comment] 2019-05-23 21:04
ok, I acknowledge the issue and will try to think of a possible fix. 
I guess the uuid used as a snapshot name must be the repair session id, but I'm not sure if we can get that information back when we trigger the segment.
We need to make sure the snapshots we'll be clearing are indeed leftovers from failed segments, otherwise we'll do more harm than good.

**Comment by adejanovski** [comment] 2019-05-29 12:30
After making some research it appears we cannot do much on the Reaper side to address this issue.
The problem was addressed in Cassandra by having ephemeral snapshots (the ones created for repairs) upon startup : https://issues.apache.org/jira/browse/CASSANDRA-7357

Reaper cannot detect ephemeral snapshots as that information isn't returned by Cassandra through JMX (it's just a special file stored in the snapshot dir that marks it as ephemeral). We cannot get the repair session id under which the repair session is generated either, so we can't link a snapshot to a repair segment.

Scheduled/manual rolling restarts of clusters can fix this issue, as sad as it looks as a workaround.
Another possibility is to use `PARALLEL` as repair parallelism (instead of DC Aware or Sequential) which won't generate snapshot but instead build the Merkle trees on all replicas at the same time (which could impact read latencies to some extent).

**Closed as completed by adejanovski** 2019-05-29 12:30 UTC
