### ISSUE TITLE
Reaper 2.2.4 still does not show snapshots

### ISSUE THREAD

**Issue by saphireee** [thelastpickle/cassandra-reaper#1046] opened 2021-04-09 13:10 UTC
List of snapshoots is empty. Older version 2.2.1 shows it but 2.2.3 not.

**Spotted on 2.2.3 (6c0281c)**

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-219) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-219

**Comment by saphireee** [comment] 2021-04-27 10:52
version 2.2.4 also does not show snapshots

**Comment by averzicco** [comment] 2021-08-05 12:06
version `2.3.1` also does not show snapshots.

I've tried to debug the issue and apparently seems caused by this [check](https://github.com/thelastpickle/cassandra-reaper/blob/e64b689313a30e83fe68409cd6b294ef8b5b585f/src/server/src/main/java/io/cassandrareaper/jmx/ClusterFacade.java#L701-L705):
```
      if (context.config.getDatacenterAvailability().isInCollocatedMode()
          && context.jmxConnectionFactory.getHostConnectionCounters().getSuccessfulConnections(
              host.getHostname()) >= 0) {
        return SnapshotProxy.create(connect(host)).listSnapshots();
      }
```

in particular `context.config.getDatacenterAvailability().isInCollocatedMode()` return false when the `datacenterAvailability` configuration setting is `ALL` based on [this](https://github.com/thelastpickle/cassandra-reaper/blob/e64b689313a30e83fe68409cd6b294ef8b5b585f/src/server/src/main/java/io/cassandrareaper/ReaperApplicationConfiguration.java#L641-L666):
```
  public enum DatacenterAvailability {
    /* We require direct JMX access to all nodes across all datacenters */
    ALL,
    /* We require jmx access to all nodes in the local datacenter */
    LOCAL,
    /* Each datacenter requires at minimum one reaper instance that has jmx access to all nodes in that datacenter */
    EACH,
    /* Sets Reaper in sidecar mode where each Cassandra node has a collocated Reaper instance */
    SIDECAR;


    /**
     * Check if the current datacenter availability mode is to have collocation between Reaper and a DC/node.
     * @return true if we're in a collocated mode, false otherwise
     */
    public boolean isInCollocatedMode() {
      switch (this) {
        case LOCAL:
        case SIDECAR:
        case EACH:
          return true;
        default:
          return false;
      }
    }
  }
  ```

**Comment by saphireee** [comment] 2021-08-05 12:53
Yes, changing to LOCAL do the trick and reaper shows snapshots so this is the case.

> in particular `context.config.getDatacenterAvailability().isInCollocatedMode()` return false when the `datacenterAvailability` configuration setting is `ALL` based on [this](https://github.com/thelastpickle/cassandra-reaper/blob/e64b689313a30e83fe68409cd6b294ef8b5b585f/src/server/src/main/java/io/cassandrareaper/ReaperApplicationConfiguration.java#L641-L666):
> 
> ```
>   public enum DatacenterAvailability {
>     /* We require direct JMX access to all nodes across all datacenters */
>     ALL,
>     /* We require jmx access to all nodes in the local datacenter */
>     LOCAL,
>     /* Each datacenter requires at minimum one reaper instance that has jmx access to all nodes in that datacenter */
>     EACH,
>     /* Sets Reaper in sidecar mode where each Cassandra node has a collocated Reaper instance */
>     SIDECAR;
> 
> 
>     /**
>      * Check if the current datacenter availability mode is to have collocation between Reaper and a DC/node.
>      * @return true if we're in a collocated mode, false otherwise
>      */
>     public boolean isInCollocatedMode() {
>       switch (this) {
>         case LOCAL:
>         case SIDECAR:
>         case EACH:
>           return true;
>         default:
>           return false;
>       }
>     }
>   }
> ```

**Comment by adejanovski** [comment] 2022-03-25 07:37
Fixed in 3.x

**Closed as completed by adejanovski** 2022-03-25 07:37 UTC
