### ISSUE TITLE
Unable to set custom JMX posts

### ISSUE THREAD

**Issue by erangaeb** [thelastpickle/cassandra-reaper#861] opened 2020-03-05 06:30 UTC
I wanted to set customer JMX host, ports in reaper. I have tried it with the environment variable `REAPER_JMX_PORTS`. It did not work, following is the configuration I have used. 

```
environment:
  - REAPER_JMX_AUTH_USERNAME=reaperUser
  - REAPER_JMX_AUTH_PASSWORD=reaperPass
  - REAPER_STORAGE_TYPE=memory
  # use localhost since I have done ssh port forwarding from cassadnra nodes to reaper docker
  - REAPER_JMX_PORTS={"127.0.0.1":17199, "127.0.0.1":27199}
```

I also tried to set the host, port in `/etc/cassandra-reaper.yaml` like below. It also not working. 

```
jmxPorts:
  localhost: 17199
  localhost: 27199
```

Even though specified customer host, ports, It always take the IP addresses of the Cassandra nodes and default JMX ports `7199`. Following is the error I'm getting, `172.17.0.2` is one of the IP address of the Cassandra docker node. 

```
INFO   [2020-03-05 06:05:28,174] [ClusterResource] i.c.j.JmxConnectionFactory - Unreachable host: Failure when establishing JMX connection to 172.17.0.2:7199: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 172.17.0.2; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)]
ERROR  [2020-03-05 06:05:28,200] [ClusterResource] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 172.17.0.2:7199
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 172.17.0.2:7199
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:222)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:102)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:137)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:802)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:786)
	at io.cassandrareaper.jmx.ClusterFacade.getNodesStatus(ClusterFacade.java:200)
	at io.cassandrareaper.resources.ClusterResource.lambda$getEndpointState$4(ClusterResource.java:369)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 172.17.0.2:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:264)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:168)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:213)
	... 14 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 172.17.0.2; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:282)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:221)
	... 16 common frames omitted
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 172.17.0.2; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at io.cassandrareaper.jmx.JmxProxyImpl.lambda$connectWithTimeout$0(JmxProxyImpl.java:281)
	... 4 common frames omitted
Caused by: javax.naming.ServiceUnavailableException: null
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 6 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 172.17.0.2; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
	... 11 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 16 common frames omitted
INFO   [2020-03-05 06:05:28,201] [ClusterResource] i.c.j.JmxConnectionFactory - Unreachable host: Failure when establishing JMX connection to 172.17.0.2:7199: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 172.17.0.2; nested exception is:
```

**Comment by adejanovski** [comment] 2020-03-27 13:59
Hi,

it looks like you're trying to set 2 different JMX ports for localhost, but the error message refers to node `172.17.0.2`.
If you have specific ports for each node in the cluster, you'll have to add a line for each of these nodes in the yaml:

```
jmxPorts:
  172.17.0.2: 17199
  172.17.0.3: 27199
  ...
```

If you have a single JMX port, which is different than the default, then you can set this port through the UI or the REST API when adding the cluster with its seed node. There's an argument for that.

**Comment by adejanovski** [comment] 2020-04-10 13:41
@erangaeb, 
I'll close this ticket as the problem is most likely a misconfiguration.
Feel free to reopen in case you're still having an issue here.
Thanks!

**Closed as completed by adejanovski** 2020-04-10 13:41 UTC
