### ISSUE TITLE
Add Run Now button for scheduled repairs

### ISSUE THREAD

**Issue by elsmorian** [thelastpickle/cassandra-reaper#290] opened 2017-12-04 15:26 UTC
I have had the situation where it would be really handy to trigger a scheduled repair at that time, and not either have to wait for it to schedule automatically, or go in and enter the run time so it starts shortly.

A Run Now button on schedule repairs would be really handy!

**Comment by mrwulf** [comment] 2017-12-06 18:27
Same as #241 ?

**Comment by elsmorian** [comment] 2017-12-07 13:08
Aha, sorry managed to miss this in my search. Yup that would cover it!

**Comment by adejanovski** [comment] 2018-01-12 11:13
Closing as duplicate of #241

**Closed as completed by adejanovski** 2018-01-12 11:13 UTC
