### ISSUE TITLE
Segments that exceed the Reaper's timeout fail repeatedly, stalling repairs

### ISSUE THREAD

**Issue by treuherz** [thelastpickle/cassandra-reaper#990] opened 2020-11-10 09:34 UTC
When running Reaper, I often seem to end up with most segments running just fine, well under the timeout, and then one that times out over and over again. Is there any way to try to detect this scenario and automatically split that segment in half? As it stands, an anomalously long-running segment can stall an entire multi-day repair process.

It may be that there's something I'm missing that would help here instead, like a way to change the segment timeout while a repair is running. I'd also be happy to pause Reaper and repair the segment myself with nodetool, but it's not clear which flags for that will replicate Reaper's behaviour the best, and I don't want to risk messing something up when I reactivate its repair.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-256) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-256

**Comment by adejanovski** [comment] 2021-01-19 09:56
I was thinking of another solution for this: extend the timeout for failing segments to give them a chance to go through without repeatedly failing. 
Changing the list of segments could be more challenging to achieve in a consistent way and require expensive coordination between Reaper instances.

Also, I would use that change to move the segment timeout from a Reaper configuration setting to be a repair specific configuration setting. This would allow to automatically adjust the timeout on existing schedules if we see that lots of segments in a repair run required to use a bigger timeout.
It would allow more flexibility in changing timeouts as well, since it wouldn't require to change the value on all reaper instances and restart them.

**Comment by treuherz** [comment] 2021-01-19 11:26
I think that would solve the same problem, yeah.

I don't know how reaper currently picks which segments to run next, but the current system results in it appearing to aggressively retry a failing segment. Another tactic to solve the problem of "this failing segment stalls my repair" might be to move repeatedly-failing segments further down the queue. 

If it's all the same to you, I'll change the issue title to reflect the problem rather than my suggested solution

**Comment by adejanovski** [comment] 2021-01-19 12:54
Segments are actually shuffled, but there's still a notion of "parallel ranges" which can lead to this behavior in case there aren't many more segments available in one of the ranges.
We're removing this notion as it's only valid for clusters not using vnodes (which definitely aren't the norm) and you should see some great improvements coming soon in 2.2.
Thanks for renaming the issue 👍

**Comment by eriksw** [comment] 2021-01-28 03:05
Possibly a silly question, but why is there a segment timeout in the first place?

If it hasn't errored out, under what circumstances is it better to abort and reattempt the exact same range repair?

**Comment by adejanovski** [comment] 2021-01-28 07:55
When Reaper was created, repair sessions had a tendency to get stuck forever under some circumstances.
The solution that was designed then was to have a timeout for segments and retry them, assuming they got stuck.
I think the idea is still valid today because it is challenging to either reproduce the issue or guarantee it cannot happen. So we still need to assume it can still happen.
At the same time, It's also a good indicator that we don't have enough segments as they are taking too long. If segments time out, it probably means that we're generating too much overstreaming and need to have less token ranges per segment.
The 30 minutes default is probably a little conservative though and could easily be doubled. 
Then the "adaptive repair" feature could apply the following rules that I apply when configuring repairs:

- If only a few segments timed out and needed an timeout extension, raise the timeout limit on the schedule
- If many segments timed out, raise the number of segments per node on the schedule

**Comment by adejanovski** [comment] 2022-03-25 09:05
This was fixed in 3.1 with adaptive repairs.

**Closed as completed by adejanovski** 2022-03-25 09:05 UTC
Labels: enhancement
