### ISSUE TITLE
Executing SegmentRunner failed: timeout value is negative

### ISSUE THREAD

**Issue by MALPI** [thelastpickle/cassandra-reaper#138] opened 2017-07-12 07:11 UTC
Hey there,

creaper seems to be looping in a strange state.

A repair on one of our keyspaces was triggered this morning.

'INFO  com.spotify.reaper.cassandra.JmxProxy  Triggering repair of range (-6689990158689412391,-6688222914336266530] for keyspace "keyspace1" on host 192.168.0.1, with repair parallelism parallel, in cluster with Cassandra version '3.9' (can use DATACENTER_AWARE 'true'), for column families: []`

Next logs are:

```
INFO Repair for segment 416 started, status wait will timeout in 3000000 millis  
WARN  com.spotify.reaper.service.SegmentRunner  repair session failed for segment with id '416' and repair number '31'  
INFO  com.spotify.reaper.service.SegmentRunner  Postponing segment 416  
INFO  com.spotify.reaper.service.SegmentRunner  Repair command 31 on segment 416 returned with state NOT_STARTED  
ERROR com.spotify.reaper.service.RepairRunner  Executing SegmentRunner failed: timeout value is negative  
INFO  com.spotify.reaper.service.RepairRunner  Next segment to run : 418  
INFO  com.spotify.reaper.service.SegmentRunner  SegmentRunner declined to repair segment 418 because only one segment is allowed at once for incremental repairs  
INFO  com.spotify.reaper.service.SegmentRunner  Postponing segment 418  
```
Now it seems to be stuck in a loop and postponing segments. Any idea what's going wrong here? The cluster is up&running in a healthy state.

**Comment by MALPI** [comment] 2017-07-12 07:25
After checking cassandra logs, it seems like that the repair is not running through due to a bug in cassandra.

https://issues.apache.org/jira/browse/CASSANDRA-13335

Have to see how to work around that.

**Comment by adejanovski** [comment] 2017-07-28 16:15
Closing the issue as it is not caused by Reaper.

**Closed as completed by adejanovski** 2017-07-28 16:15 UTC
