### ISSUE TITLE
Reaper with datacenterAvailability EACH tries to connect cross DC

### ISSUE THREAD

**Issue by mparkachov** [thelastpickle/cassandra-reaper#522] opened 2018-08-14 07:28 UTC
I have a cassandra cluster with 2 DCs and correspondingly 2 cassandra reapers in each DC with Cassandra backend. The datacenterAvailability is set to EACH , but when I look in the reaper log file I see a lot of errors where reaper tries to connect cross data center:

`
2018-08-14 00:01:46,930 - INFO  - [i.c.s.SegmentRunner] - Trying to get metrics from remote DCs for 10.10.10.12 in secondary of tst

2018-08-14 00:01:46,942 - ERROR - [i.c.j.JmxConnectionFactory] - Failed creating a new JMX connection to 10.10.10.12
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.10.10.12:7199
.... long exception log skipped.
`

I see the same behaviour in both reapers but with different DC. Although I could reach JMX port cross DC, the full JMX connection is not possible.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-363) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-363

**Comment by adejanovski** [comment] 2018-08-14 08:14
Hi @mparkachov,

this is somewhat the expected behavior in multi region clusters with Reaper. If you're using each, then what'll happen is that Reaper in DC1 will send a request for metrics of DC2 nodes through the Cassandra backend, and all Reapers will try to answer that request (to be fair, even Reapers in DC1 will try and fail if the JMX port is not accessible). It's not easy to determine which DC a Reaper is in, but we had something in mind that could optimize this process.

You mention that cross DC JMX should be possible in your cluster ? Maybe the connections are timing out then ? Do note that using `EACH` will simply skip Reapers from querying remote DCs directly and go through the metrics request system directly. If you wanted to have all Reapers connect directly to all nodes (and figured why the JMX connection is failing) then you would have to switch to `ALL` insteead.

**Comment by mparkachov** [comment] 2018-08-14 09:44
Thanks for detailed explanation. Unfortunately our network is a bit "complicated", but I definitely could not make cross DC JMX connection. Reaper does skip remote host after a while with timeout exception:

`
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.10.10.12:7199
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:267)
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:174)
        at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:223)
        ... 39 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:285)
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:234)
`

> Do note that using EACH will simply skip Reapers from querying remote DCs directly and go through the metrics request system directly.

I think this is exactly what is not working. Even with EACH reaper still tries to query remote DC, as mentioned in original error message.

**Comment by adejanovski** [comment] 2018-08-14 09:55
After a while, Reaper will "understand" that some nodes are not worth connecting to, but not in all situations. 
Do you have one Reaper instance at least in each datacenter ?
Do you manage to have Reaper work as expected (repairs making progress, etc...) or do you have some weird behaviors ?

**Comment by mparkachov** [comment] 2018-08-14 14:47
I do have reaper instance in each DC and it is working (repairing, scheduling etc.) What is not working is reaper unable to show snapshots, it tries to connect cross DC and this weird error message with ERROR log level. 

I tried to investigate another unrelated issue, looked in log file, and was surprised to see 150 or so errors per day in log file.

**Comment by michaelsembwever** [comment] 2018-08-15 09:01
@adejanovski is this why the snapshot integration tests are annotated with `@all_nodes_reachable` (because the snapshot functionality actually doesn't work with EACH) ?

**Comment by adejanovski** [comment] 2018-08-28 08:30
Yes, snapshots in multi region clusters are still unsupported. 
We need to schedule snapshot execution/retrieval through the backend just as we do for metrics and repairs if we want to get that working in this setup.

**Comment by adejanovski** [comment] 2019-07-10 13:44
@kolpator, do you have one Reaper instance in each datacenter?
Are repairs making progress as they should?
Are you having this problem only with snapshot related operations?

**Comment by kolpator** [comment] 2019-07-11 10:20
@adejanovski  yes we have 2 reaper instance,  each for one dc,  it seems repairing works ( its still repairing  eta 2 days...),   each reaper instance still trying to access remote dc nodes via jmx... is it normal ? what i expecting is; if another reaper instance exist in remote dc, then each reaper instance only access local nodes  am i wrong ?

**Comment by adejanovski** [comment] 2019-07-11 11:45
Reaper doesn't actually know which DC it is attached to. It tries to build a map of nodes that can be accessed for repairs, but it'll still try to connect to all nodes every once in a while, so that behavior doesn't surprise me.
There are actually good reasons to this. If a node isn't reachable now, it doesn't mean it won't be accessible later (could just be down at that specific time), so we cannot blacklist them.
It has proven fairly hard to pin Reaper to a specific DC given we offer several different architectures. 
We have a few features that we'll be working on soon and will require to deal more precisely with how Reaper instances connect to nodes, so I'd expect some improvements on that front soon.

**Comment by mattheworiordan** [comment] 2020-03-03 11:35
Hi @adejanovski is there any update on this?  I just updated to the latest version 2.0.2 and the issue persists.

When I inspect our reaper logs, it's quite challenging to get anything useful from them as they're literally polluted with frequent occurrences of the following, for every Cassandra node in every other DC:

```
ERROR  [2020-03-03 11:28:44,930] [ClusterResource] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 1.2.3.4:7199
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 1.2.3.4:7199
        at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:222)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:102)
        at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:137)
        at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:802)
        at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:786)
        at io.cassandrareaper.jmx.ClusterFacade.getNodesStatus(ClusterFacade.java:200)
        at io.cassandrareaper.resources.ClusterResource.lambda$getEndpointState$4(ClusterResource.java:369)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 1.2.3.4:7199
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:264)
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:168)
        at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:213)
        ... 14 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:282)
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:221)
        ... 16 common frames omitted
```

In response to your points:

> Reaper doesn't actually know which DC it is attached to

Could we not simply add a new configuration/env var to explicitly specify this?

> There are actually good reasons to this. If a node isn't reachable now, it doesn't mean it won't be accessible later (could just be down at that specific time), so we cannot blacklist them.

Sure, but you could use `system.peers` to work out which nodes are in the same DC (if provided in the config) and only attempt connection to nodes that match the DC, at least once bootstrapped anyway.

> We have a few features that we'll be working on soon and will require to deal more precisely with how Reaper instances connect to nodes, so I'd expect some improvements on that front soon.

Ok, I'd be happy to help you test this / contribute in some way.

**Comment by adejanovski** [comment] 2022-03-25 13:56
This should've been fixed in 3.x versions of Reaper.
Feel free to reopen if the behavior still happens.

**Closed as completed by adejanovski** 2022-03-25 13:56 UTC
