### ISSUE TITLE
Segments per node raises an incorrect error message

### ISSUE THREAD

**Issue by piotrmaslanka** [thelastpickle/cassandra-reaper#908] opened 2020-04-29 15:37 UTC
Giving Segments per node larger than 1000 gives the error message that it can't be larger than 100000. This is very misleading.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-433) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-433

**Comment by adejanovski** [comment] 2022-03-25 12:20
Closing as duplicate of #743

**Closed as completed by adejanovski** 2022-03-25 12:20 UTC
Labels: low hanging fruit
