### ISSUE TITLE
repair manager fails with IllegalStateException: endTime can only be set if segment is DONE

### ISSUE THREAD

**Issue by vrischmann** [thelastpickle/cassandra-reaper#457] opened 2018-06-24 13:09 UTC
Hi,

I use Cassandra 2.2.12 as storage and today I saw this error in the reaper logs:

    ERROR  [2018-06-24 13:06:09,148] [pool-1-thread-1] i.c.ReaperApplication - Couldn't resume running repair runs
    io.cassandrareaper.ReaperException: java.lang.IllegalStateException: endTime can only be set if segment is DONE
            at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:103)
            at io.cassandrareaper.ReaperApplication.lambda$run$0(ReaperApplication.java:267)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.IllegalStateException: endTime can only be set if segment is DONE
            at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
            at io.cassandrareaper.core.RepairSegment$Builder.build(RepairSegment.java:228)
            at io.cassandrareaper.storage.CassandraStorage.createRepairSegmentFromRow(CassandraStorage.java:813)
            at io.cassandrareaper.storage.CassandraStorage.getSegmentsWithState(CassandraStorage.java:840)
            at io.cassandrareaper.service.RepairManager.lambda$abortAllRunningSegmentsWithNoLeader$0(RepairManager.java:111)
            at java.lang.Iterable.forEach(Iterable.java:75)
            at io.cassandrareaper.service.RepairManager.abortAllRunningSegmentsWithNoLeader(RepairManager.java:109)
            at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:98)
            ... 8 common frames omitted

It was still logging some stuff but I decided to restart reaper, now after starting up it doesn't log anything other than this error, so I assume it's not making progress.

**Comment by michaelsembwever** [comment] 2018-06-26 11:40
What version of Reaper were you using?
These assertions/preconditions have ironed out a number of false presumptions about the code, and so far most (we believe) have been addressed.

**Comment by vrischmann** [comment] 2018-06-26 11:53
I believe I was using 32c779ff2e7a923ed3570c1b206eb0e81ff38c96

**Comment by adejanovski** [comment] 2018-06-26 12:22
@vrischmann : did you by any chance set a TTL on the `repair_run` table ?

**Comment by vrischmann** [comment] 2018-06-26 12:35
No, no TTL

**Comment by amorton** [comment] 2018-07-03 20:57
@vrischmann is this still a problem and is it preventing you using reaper ? 

Could you also add a dump of the contents of the `repair_run` table using `COPY` command in `cqlsh`.

**Comment by vrischmann** [comment] 2018-07-09 14:08
Hi, sorry for the late reply.

Last time I was using reaper it still was a problem. However I had to stop using reaper for other reasons and right now I don't have time to look into it.

**Comment by michaelsembwever** [comment] 2018-07-11 12:32
Fixed by https://github.com/thelastpickle/cassandra-reaper/pull/476

**Closed as completed by michaelsembwever** 2018-07-11 12:32 UTC

**Comment by myoussefakamai** [comment] 2019-04-19 20:05
I am getting this error using Cassandra 2.2.14 and Cassandra Reaper 1.4.1

`ERROR  [2019-04-19 20:03:15,236] [dw-88 - GET /cluster/cluster1] i.d.j.e.LoggingExceptionMapper - Error handling a request: 1b31810677d2c06b
java.lang.IllegalStateException: endTime can only be set if segment is DONE`

**Comment by michaelsembwever** [comment] 2019-04-21 03:52
@myoussefakamai could you post the complete stacktrace from the logs for the `IllegalStateException: endTime can only be set if segment is DONE`
there are different ways this might happen, and the code changed a number of times to improve this situation, so we need exact details to look for the cause beyond what is a common symptom.
