### ISSUE TITLE
"Failed purging repair runs from history"

### ISSUE THREAD

**Issue by maciej-lasyk** [thelastpickle/cassandra-reaper#503] opened 2018-07-31 09:27 UTC
**Spotted on 1.2.2 (0446d2d)**

After finishing last repair got this in reaper's log:

> ERROR  [2018-07-31 08:59:09,217] [ReaperApplication-scheduler] i.c.ReaperApplication - Failed purging repair runs from history
java.lang.NullPointerException: null
        at io.cassandrareaper.service.PurgeManager.lambda$purgeRepairRunsByHistoryDepth$1(PurgeManager.java:90)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1462)
        at io.cassandrareaper.service.PurgeManager.purgeRepairRunsByHistoryDepth(PurgeManager.java:89)
        at io.cassandrareaper.service.PurgeManager.purgeDatabase(PurgeManager.java:66)
        at io.cassandrareaper.ReaperApplication.lambda$schedulePurge$1(ReaperApplication.java:305)
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Got RDS backend configured and working flawlessly for the last couple of months on Reaper 1.1.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-361) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-361

**Comment by adejanovski** [comment] 2018-08-03 06:39
Hi @maciej-lasyk,

this suggests that one of the terminated repair runs has no end time, which shouldn't be possible (we have assertions in place to detect this).
Could you check the database to see if you have such repair runs ?
Has the error appeared again in the logs after this ?

**Comment by maciej-lasyk** [comment] 2018-12-19 13:02
@adejanovski funny thing is - all of the ABORTED runs have empty end_time: https://gist.github.com/maciej-lasyk/070d3e912fe3db75eefa61a4ffbcc2d3

And this is still a case after upgrading to the last version. It's not a big deal, as it's only complaining in logfiles (and sometimes alerting us as it is an ERROR severity) but fortunately happens only when starting Reaper.

**Comment by SesquipedalianDefenestrator** [comment] 2019-05-01 21:52
FYI, https://github.com/thelastpickle/cassandra-reaper/issues/603 is a duplicate of this and the fix should be in for 1.4.2.

**Comment by adejanovski** [comment] 2022-03-25 13:39
These issues with missing end times were fixed a while ago.
Closing this ticket.

**Closed as completed by adejanovski** 2022-03-25 13:39 UTC
