### ISSUE TITLE
Reapairs running forever

### ISSUE THREAD

**Issue by schode** [thelastpickle/cassandra-reaper#925] opened 2020-05-18 15:50 UTC
Hi, I scheduled Cassandra repairs for our production cluster(5 nodes) but it seems like its ever running, it used to take two days to complete 269 segments and 880 GB of data. I observed this issue after rebooting the Cassandra cluster a month ago. I had to abort the process as it is running for 3 weeks. Can someone suggest me how to fix it?

I found in logs
INFO   [som-prod-cluster:00000000-0000-0012-0000-000000000000:00000000-0000-272a-0000-000000000000] i.c.s.RepairRunner - postponed repair segment 00000000-0000-272a-0000-000000000000 because one of the hosts (10.xx.xx.xx) was already involved in a repair

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-443) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-443

**Comment by adejanovski** [comment] 2020-05-19 10:50
Hi, could you check if segments have a fail count higher than 0 in the segment list? Also, how long do completed segments lasted?
It could be that your segments cannot complete within 30 minutes, which is the default timeout.
The info message you're mentioning is normal as reaper will only allow one repair per node at all time, and will postpone segments that would conflict with running repairs.

**Comment by schode** [comment] 2020-05-19 15:42
Hi Adejanovski, thanks for the reply. I see failed count 1 for one of the segment repaired but many segments which are yet to start have more failed counts as high as 10. Coming to the duration of repair time to complete the repair segments as low as 6 mins to as high as 30 mins.

**Comment by adejanovski** [comment] 2020-05-19 16:01
ok I think your number of segments is too low and the segments can last for too long. This forces Reaper to terminate repair sessions, which can leave Cassandra in some funny state.
I recommend to:
- Abort running repairs
- roll restart the cluster to bring it back to a clean state
- Create a new repair with double the segments and see how it goes

You should monitor the fail count and segment duration to see if it fits. If not, you can set a higher timeout in the reaper configuration and use 60 minutes for example.

**Comment by schode** [comment] 2020-05-21 14:26
Hi Alexander, I tried with rolling restart and doubling the segments but it is taking longer than before so we have to abort the process and start manually. We are using reaper 2.0.2 and Cassandra 3.10. The repairs are running fine in other environments. Please find the attached logs from the reaper and Casandra node. 
[prod_cassandra_system_log.txt.zip](https://github.com/thelastpickle/cassandra-reaper/files/4662922/prod_cassandra_system_log.txt.zip)
[prod_reaper_log.txt.zip](https://github.com/thelastpickle/cassandra-reaper/files/4662923/prod_reaper_log.txt.zip)

**Comment by adejanovski** [comment] 2020-06-11 08:12
Hi @schode,
this is most probably caused by #863 which was fixed in v2.0.4.
I'd recommend an upgrade to fix your issue.

**Comment by adejanovski** [comment] 2022-03-25 08:13
Closing due to inactivity.

**Closed as completed by adejanovski** 2022-03-25 08:13 UTC
