### ISSUE TITLE
Notification Email - Enhancement

### ISSUE THREAD

**Issue by JIppolito** [thelastpickle/cassandra-reaper#79] opened 2017-04-06 15:25 UTC
Add a field to enter an email address to notify when a repair starts/stops/fails.  Currently have a crude ruby script which runs via cron and checks to see if a repair is running and to send an email out

**Comment by rustyrazorblade** [comment] 2017-04-06 16:52
Interesting, but we're looking to make something a little more flexible than email.  Take a look at #11.  I think we're looking to go down an HTTP callback route.  In the spirit of flexible design, we'll probably make the callback part pluggable & provide an HTTP implementation.

**Comment by JIppolito** [comment] 2017-04-06 17:04
probably should have worded that better as the current script i have is going to plugin to graphite/grafana that we use, not just email. Didnt see the pluggable observers issue/enhancement.

**Comment by adejanovski** [comment] 2017-08-26 16:21
Let's close this as duplicate of #11

**Closed as completed by adejanovski** 2017-08-26 16:21 UTC
