### ISSUE TITLE
Reaper not starting if cluster name is shorter than 4 characters

### ISSUE THREAD

**Issue by mparkachov** [thelastpickle/cassandra-reaper#767] opened 2019-10-16 09:12 UTC
Found in version: 1.4.6

Backend cassandra cluster with name "aa"

Cassandra reaper on start fails with exception:

```
java.lang.IllegalArgumentException: Empty key
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at io.cassandrareaper.resources.auth.ShiroJwtProvider.getSigningKey(ShiroJwtProvider.java:63)
        at io.cassandrareaper.resources.auth.ShiroJwtProvider.<init>(ShiroJwtProvider.java:44)
```

To reproduce:

export JWT_SECRET=aa
start reaper -> exception

export JWT_SECRET=aabb
start reaper -> ok

The part bellow is responsible for this behaviour:

https://github.com/thelastpickle/cassandra-reaper/blob/842eb0286536407e97d03e70c795ea9caec7fc24/src/server/src/main/java/io/cassandrareaper/resources/auth/ShiroJwtProvider.java#L57-L63

And it will probably not work for postgress backend at all.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-408) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-408

**Comment by jvf** [comment] 2020-03-17 11:16
As a user of a few clusters with three-letter-names I can painfully attest: This bug still persists in Version 2.0.3! Any chance of getting a fix anytime soon?

**Comment by jvf** [comment] 2020-03-17 11:24
A workaround is to disable authentication by commenting out the `accessControl` block in the `cassandra-reaper.yaml` (beware of the implications!).

**Comment by michaelsembwever** [comment] 2020-03-17 13:07
The correct approach here is to define the environment variable `JWT_SECRET`. This can be done in the `cassandra-reaper` file.

**Comment by jvf** [comment] 2020-03-17 17:19
I can confirm, setting `JWT_SECRET` to a string of size >= 4 totally solves the problem. 

I would still consider setting `JWT_SECRET` manually a workaround, in my opinion Cassandra Reaper should fall back to a string if the cluster name is shorter than 4 characters. At least this should be documented somewhere.

If you don't like to manipulate the startup script shipped by some software (I don't) you can just set `JWT_SECRET` in the environment calling the `cassandra-reaper` script. For example, if using `systemd`, add a minimal `override.conf` in `/etc/systemd/system/cassandra-reaper.service.d/override.conf` with the following content:

```
[Service]
Environment=JWT_SECRET=<some_random_string_of_size_four_or_larger>
```

**Comment by sam-goldberg** [comment] 2021-06-10 14:37
I have a use case where setting JWT_SECRET in /etc/profile.d/reaper.sh does not appear to successfully work around this issue. 

Setting accessControl does work, but it's not a viable solution due to security concerns.

Is it possible to get a fix for this issue?

**Comment by sam-goldberg** [comment] 2021-06-17 21:09
@michaelsembwever is a fix for this issue planned in future updates?

**Comment by burmanm** [comment] 2021-09-02 14:52
JWT_SECRET should be a Base64 encoded string and shortest Base64-string is actually 4 characters, which is where the limitations to JWT_SECRET comes from.

**Closed as completed** 2021-09-03 18:33 UTC

**Comment by weisslj** [comment] 2022-06-01 05:10
After this change, if a `JWT_SECRET` is used, that is an invalid Base64 string, the error message is hardly better :disappointed::

```
May 24 16:36:29 reaper cassandra-reaper[687104]: Using reaper in target
May 24 16:36:33 reaper cassandra-reaper[687104]: java.lang.IllegalArgumentException: Last unit does not have enough valid bits
May 24 16:36:33 reaper cassandra-reaper[687104]:         at java.base/java.util.Base64$Decoder.decode0(Base64.java:766)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.cassandrareaper.resources.auth.ShiroJwtProvider.getSigningKey(ShiroJwtProvider.java:68)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.cassandrareaper.resources.auth.ShiroJwtProvider.<init>(ShiroJwtProvider.java:45)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:235)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:90)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.dropwizard.cli.Cli.run(Cli.java:78)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.dropwizard.Application.run(Application.java:94)
May 24 16:36:33 reaper cassandra-reaper[687104]:         at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:102)
```

Posting here, also so that users with the same problem can find the solution easier ...
