### ISSUE TITLE
Reaper generating tons of tiny sstables?

### ISSUE THREAD

**Issue by ron-ayla** [thelastpickle/cassandra-reaper#627] opened 2019-03-14 21:05 UTC
I’m not sure that this is the correct forum to ask this question, so please direct me to the correct forum if this is incorrect.

I have setup Cassandra Reaper to run repair on my Apache Cassandra cluster.  I was initially running repair with the defaults, and experienced lots of repeated failures on the same segment.  I think this was because Reaper was running into a 30 minute timeout.  In order to get around this, I specified a very large Segments per node parameter.  I started off with smaller numbers but ended up with a number of 500 in order to make it under the 30 minute limit per segment.

Now I notice a huge number of tiny sstables, and there are frequent pairs of sstables that are identical to each other.  Here is the sort of thing that I see:

ubuntu@cass-70145-stage:/cassandra/data/datapoint/datapoints_v2-0e284ca03a4411e9bdc47572a99f96c4$ ls -l *-big-Data.db|wc -l
562
ubuntu@cass-70145-stage:/cassandra/data/datapoint/datapoints_v2-0e284ca03a4411e9bdc47572a99f96c4$ ls -l *-big-Data.db|tail
-rw-r--r-- 1 cassandra cassandra         791 Mar 14 19:51 mc-6172-big-Data.db
-rw-r--r-- 1 cassandra cassandra     7907515 Mar 14 19:55 mc-6173-big-Data.db
-rw-r--r-- 1 cassandra cassandra  6354573340 Mar 14 20:15 mc-6174-big-Data.db
-rw-r--r-- 1 cassandra cassandra         487 Mar 14 19:59 mc-6175-big-Data.db
-rw-r--r-- 1 cassandra cassandra         310 Mar 14 19:59 mc-6176-big-Data.db
-rw-r--r-- 1 cassandra cassandra         310 Mar 14 19:59 mc-6177-big-Data.db
-rw-r--r-- 1 cassandra cassandra        1966 Mar 14 19:59 mc-6178-big-Data.db
-rw-r--r-- 1 cassandra cassandra        1966 Mar 14 19:59 mc-6179-big-Data.db
-rw-r--r-- 1 cassandra cassandra         487 Mar 14 19:59 mc-6180-big-Data.db
-rw-r--r-- 1 cassandra cassandra  4235694830 Mar 14 20:27 mc-6181-big-Data.db
ubuntu@cass-70145-stage:/cassandra/data/datapoint/datapoints_v2-0e284ca03a4411e9bdc47572a99f96c4$ diff mc-6178-big-Data.db mc-6179-big-Data.db
ubuntu@cass-70145-stage:/cassandra/data/datapoint/datapoints_v2-0e284ca03a4411e9bdc47572a99f96c4$

Do you have any suggestions for how to avoid this situation, or any suggestions in general about how I am running Reaper?

Many thanks,

Ron
**Spotted on 1.4.0 (4c225e6)**

**Comment by michaelsembwever** [comment] 2019-03-17 05:51
@adejanovski have you any idea what, in relation to the `segments per node` setting, could be causing this?

**Comment by adejanovski** [comment] 2019-03-18 10:45
Hi @ron-ayla, 

Reaper isn't directly responsible for what you're seeing.
Each segment will cover a specific range of tokens, which in your case exceed the 256 vnodes per node (which are already creating a big overhead).
Each replica for this range of token will generate a merkle tree, which has at most 32k leaves. You'll then probably end up with several tokens in the same leaf as you can have more than 32k partitions in that token range.
If only one partition has a difference, all the partitions within that leaf will get streamed between replicas. So if you have replicas A, B and C, then : 
- A will stream to B as many SSTables as there are SSTables on A that contain one of the partitions that's part of the leaf. It will also stream the same SStables to C (it's not streaming a single SSTable that's concatenating all the SSTables chunks to stream, each chunk will end up in a separately streamed sstable).
- B will stream the same partitions to A and C
- C will stream the same partitions to A and B

The more segments and the more entropy you'll have in the cluster, the more this is likely to happen.
I'm not 100% sure about why you're having similar SSTable streamed, but it means that you probably have duplicated data on the node that streamed this data, possibly due to your past failures to run repair entirely (the partitions get streamed again when you retry).
Also LCS is more likely to emphasize the problem as large tables can easily have 1000+ SSTables, which leads to more tiny sstables being streamed. This can be mitigated with a larger SSTable size in your LCS settings to reduce their number.

It is likely that if you're having a segment that fails, it's possibly because you have a corrupt sstable/index file. You should try to scrub your keyspace in order to see if this can be fixed (check the replicas for that specific segment). 500 segments per node is way over what I would recommend, we're more trying to go below 100 segments per node.
My suggestion would then be to : wait for compaction to catch up now, extend the segment timeout to 1 hour and run the repair with your previous settings. Once you get a first complete run, you should have less entropy in the subsequent runs and thus less streaming, which will make your repairs shorter.
 
But AFAIK, the problem isn't due to Reaper itself (it's just triggering repair) but more to the settings of the repairs and the state of the cluster you're repairing.

**Comment by ron-ayla** [comment] 2019-03-18 19:48
Thanks so much for your help.  I will try your suggestions.

**Comment by michaelsembwever** [comment] 2019-04-04 04:48
Closing this off. Feel free to re-open if you can link it to something specific in Reaper.

**Closed as completed by michaelsembwever** 2019-04-04 04:48 UTC
